# Generated by Django 3.0.2 on 2020-09-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200928_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamster',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
